export default {
    products: [
        {
            _id: '1',
            name: 'Full Zip Running Shirts',
            category: 'Shirts',
            image: "/src/images/product-1.png",
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name: 'Full Zip Running Shirts',
            category: 'Shirts',
            image: "/src/images/product-2.png",
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '3',
            name: 'Full Zip Running Shirts',
            category: 'Shirts',
            image: "/src/images/product-3.png",
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '4',
            name: 'Full Zip Running Shirts',
            category: 'Shirts',
            image: "/src/images/product-4.png",
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '5',
            name: 'Full Zip Running Shirts',
            category: 'Shirts',
            image: "/src/images/product-5.png",
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '6',
            name: 'Full Zip Running Shirts',
            category: 'Shirts',
            image: "/src/images/product-6.png",
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
    ],
}